"""CGAL decisions on exactly injected binary64 geometry; coordinates in mm."""

class InvalidCircleGeometryError(RuntimeError): ...
class NoCircleIntersectionError(RuntimeError): ...
class InvalidBoundaryProjectionError(RuntimeError): ...
class AmbiguousBoundaryProjectionError(RuntimeError): ...
class BoundaryProjectionDistanceError(RuntimeError): ...
class InvalidBoundaryPolygonError(RuntimeError): ...
class InvalidBoundaryNormalInputError(RuntimeError): ...
class BoundaryVertexQueryUnsupportedError(RuntimeError): ...
class InvalidBoundaryVertexDirectionError(RuntimeError): ...
class NoPositiveBoundaryCircleError(RuntimeError): ...
class BoundaryNormalConstructionError(RuntimeError): ...

class BoundaryNormalCircleProposal2:
    """Native exact world-XY construction; numerical properties are reporting only."""

    @property
    def is_stationary(self) -> bool: ...
    @property
    def p_mm(self) -> tuple[float, float]: ...
    @property
    def m_mm(self) -> tuple[float, float]: ...
    @property
    def q_mm(self) -> tuple[float, float]: ...
    @property
    def center_mm(self) -> tuple[float, float]: ...
    @property
    def guide_radius_mm(self) -> float: ...
    @property
    def clearance_mm(self) -> float: ...
    @property
    def competing_vertex_indices(self) -> list[int]: ...
    @property
    def competing_segment_indices(self) -> list[int]: ...

class BoundaryNormalCircle2:
    """Validated simple polygon, supplied-order segments, either winding; no holes."""

    def __init__(self, boundary: list[tuple[float, float]]) -> None: ...
    def query(self, segment_index: int, parameter: float, tool_radius: float) -> BoundaryNormalCircleProposal2:
        """First exact medial contact on the inward normal of a strict segment interior.

        The q-m diameter constructs the machining circle. The exact native outer
        cutter disk lies inside its medial disk; rounded reports do not certify
        independently reconstructed downstream geometry.
        """
        ...
    def query_vertex(self, vertex_index: int, inward_direction: tuple[float, float], tool_radius: float) -> BoundaryNormalCircleProposal2:
        """Query a reflex point-site normal cone, including its endpoint directions."""
        ...

def project_boundary_contact(boundary: list[tuple[float, float]], contact: tuple[float, float], maximum_distance: float) -> tuple[int, float]:
    """Choose nearest offset side exactly; report its approximate parameter."""

def disk_contains_disk(first: tuple[float, float], first_radius: float, second: tuple[float, float], second_radius: float) -> bool:
    """Test closed-disk containment, including exact tangency."""

def swept_disk_intersection(first: tuple[float, float], first_radius: float, second: tuple[float, float], second_radius: float, tool_radius: float) -> tuple[float, float]:
    """Report chord x in mm and squared height in mm² after exact existence check."""

def orientation(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> int:
    """Return -1 clockwise, 0 collinear, +1 counterclockwise."""

def corrected_engagement_cosine_squared(first: tuple[float, float], first_radius: float, second: tuple[float, float], second_radius: float, tool_radius: float) -> float:
    """Report squared chord cosine after exact corrected-intersection checks."""

class BoundaryCircleToolMismatchError(RuntimeError): ...
class BoundaryCircleSpacingError(RuntimeError): ...
class UncoveredStationaryCircleError(RuntimeError): ...
class InvalidBoundaryEngagementCapError(RuntimeError): ...
class BoundaryCircleEngagementGeometryError(RuntimeError): ...

def boundary_circle_engagement(
    previous: BoundaryNormalCircleProposal2,
    current: BoundaryNormalCircleProposal2,
    cap_chord_ratio: float,
) -> tuple[float, bool]:
    """Standard predecessor bound; conditional on its cleared outer disk."""
    ...
