from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

Float64Array = npt.NDArray[np.float64]


class ReachableDomainConstructionError(RuntimeError): ...
class InvalidReachableDomainInputError(ReachableDomainConstructionError): ...
class ReachableArrangementTopologyError(ReachableDomainConstructionError): ...
class PocketNotMachinableError(ReachableDomainConstructionError): ...
class ReachableMaterialContainmentError(ReachableDomainConstructionError): ...


class ExactRegion2:
    def clone(self) -> ExactRegion2: ...
    def contains(self, x: float, y: float) -> bool: ...
    def is_empty(self) -> bool: ...
    def component_count(self) -> int: ...
    def is_subset_of(self, other: ExactRegion2) -> bool: ...
    def exactly_equals(self, other: ExactRegion2) -> bool: ...


class ReachableDomainCertificate2:
    @property
    def strategy_version(self) -> bytes: ...
    @property
    def source_curve_records(self) -> Sequence[bytes]: ...
    @property
    def arrangement_vertex_records(self) -> Sequence[bytes]: ...
    @property
    def selected_cell_records(self) -> Sequence[bytes]: ...
    @property
    def component_records(self) -> Sequence[bytes]: ...
    @property
    def exact_cell_selection(self) -> bool: ...
    @property
    def complete_source_provenance(self) -> bool: ...
    @property
    def reachable_subset_of_design(self) -> bool: ...
    def matches_exact_inputs(
        self,
        boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> bool: ...


class ReachableDomain2:
    def __init__(
        self,
        design_boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> None: ...
    def design_region(self) -> ExactRegion2: ...
    def center_domain(self) -> ExactRegion2: ...
    def reachable_material(self) -> ExactRegion2: ...
    def unreachable_residual(self) -> ExactRegion2: ...
    def certificate(self) -> ReachableDomainCertificate2: ...
