from collections.abc import Sequence
from typing import Literal
from typing import NoReturn

import numpy as np
import numpy.typing as npt

Float64Array = npt.NDArray[np.float64]

class ReachableDomainConstructionError(RuntimeError): ...
class InvalidReachableDomainInputError(ReachableDomainConstructionError): ...
class ReachableArrangementTopologyError(ReachableDomainConstructionError): ...
class PocketNotMachinableError(ReachableDomainConstructionError): ...
class ReachableMaterialContainmentError(ReachableDomainConstructionError): ...
class ReachableMaterialPredicateGeometryError(ReachableDomainConstructionError): ...
class InvalidCoverageGeometryError(RuntimeError): ...
class CoverageTransitionError(RuntimeError): ...

class WorldXYBoundaryPointMm:
    """Native exact world-XY millimetre contact; obtained from primitives only."""

    def __new__(cls, _native_only: NoReturn) -> WorldXYBoundaryPointMm: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def reporting_xy_mm(self) -> tuple[float, float]:
        """Approximate reporting view; cannot be used as transition input."""
        ...

class ReachableBoundaryPrimitive2:
    @property
    def start(self) -> WorldXYBoundaryPointMm: ...
    @property
    def end(self) -> WorldXYBoundaryPointMm: ...
    @property
    def kind(self) -> Literal["line", "arc"]: ...
    @property
    def start_mm(self) -> tuple[float, float]: ...
    @property
    def end_mm(self) -> tuple[float, float]: ...
    @property
    def source_piece_records(self) -> Sequence[bytes]: ...
    @property
    def arc_center_mm(self) -> tuple[float, float]: ...
    @property
    def arc_radius_mm(self) -> float: ...
    @property
    def arc_counterclockwise(self) -> bool: ...

class ReachableBoundaryCycle2:
    @property
    def counterclockwise(self) -> bool: ...
    primitives: Sequence[ReachableBoundaryPrimitive2]
    def ccw_transition(self, start: WorldXYBoundaryPointMm, end: WorldXYBoundaryPointMm) -> Sequence[ReachableBoundaryPrimitive2]: ...

def build_center_boundary_cycle(
    design_boundary: Float64Array,
    holes: Sequence[Float64Array],
    tool_radius: float,
) -> ReachableBoundaryCycle2: ...

class ExactRegion2:
    def clone(self) -> ExactRegion2: ...
    def contains(self, x: float, y: float) -> bool: ...
    def is_empty(self) -> bool: ...
    def component_count(self) -> int: ...
    def is_subset_of(self, other: ExactRegion2) -> bool: ...
    def exactly_equals(self, other: ExactRegion2) -> bool: ...

class ReachableDomainCertificate2:
    @property
    def strategy_version(self) -> bytes: ...
    @property
    def source_curve_records(self) -> Sequence[bytes]: ...
    @property
    def arrangement_vertex_records(self) -> Sequence[bytes]: ...
    @property
    def selected_cell_records(self) -> Sequence[bytes]: ...
    @property
    def component_records(self) -> Sequence[bytes]: ...
    @property
    def exact_cell_selection(self) -> bool: ...
    @property
    def complete_source_provenance(self) -> bool: ...
    @property
    def reachable_subset_of_design(self) -> bool: ...
    def matches_exact_inputs(
        self,
        boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> bool: ...

class ReachableDomain2:
    def __init__(
        self,
        design_boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> None: ...
    def design_region(self) -> ExactRegion2: ...
    def center_domain(self) -> ExactRegion2: ...
    def reachable_material(self) -> ExactRegion2: ...
    def unreachable_residual(self) -> ExactRegion2: ...
    def certificate(self) -> ReachableDomainCertificate2: ...

class CutterCentreDomain2:
    @classmethod
    def build(
        cls,
        design_boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> CutterCentreDomain2: ...
    def contains(self, x: float, y: float) -> bool: ...

class ReachableMaterialPredicate2:
    @classmethod
    def build(
        cls,
        design_boundary: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
    ) -> ReachableMaterialPredicate2: ...
    def contains(self, x: float, y: float) -> bool: ...

class CoverageSweepRecord2:
    @property
    def strategy_version(self) -> bytes: ...
    @property
    def structural_record(self) -> bytes: ...
    @property
    def segment(self) -> bool: ...
    @property
    def center_x(self) -> float: ...
    @property
    def center_y(self) -> float: ...
    @property
    def first_x(self) -> float: ...
    @property
    def first_y(self) -> float: ...
    @property
    def tool_radius(self) -> float: ...
    def matches_exact_segment(
        self,
        x0: float,
        y0: float,
        x1: float,
        y1: float,
        tool_radius: float,
    ) -> bool: ...
    def matches_exact_full_circle(
        self,
        center_x: float,
        center_y: float,
        phase_x: float,
        phase_y: float,
        tool_radius: float,
    ) -> bool: ...

class Coverage2:
    def __init__(
        self,
        reachable_material: ExactRegion2,
        precleared_x: float,
        precleared_y: float,
        precleared_radius: float,
    ) -> None: ...
    def clone(self) -> Coverage2: ...
    def add_segment_sweep(
        self,
        x0: float,
        y0: float,
        x1: float,
        y1: float,
        tool_radius: float,
    ) -> CoverageSweepRecord2: ...
    def add_full_circle_sweep(
        self,
        center_x: float,
        center_y: float,
        phase_x: float,
        phase_y: float,
        tool_radius: float,
    ) -> CoverageSweepRecord2: ...
    def residual_is_empty(self) -> bool: ...
    def residual_component_count(self) -> int: ...
    def residual(self) -> ExactRegion2: ...
    def accumulated_sweeps(self) -> ExactRegion2: ...
    @property
    def residual_component_records(self) -> Sequence[bytes]: ...
    @property
    def sweep_records(self) -> Sequence[bytes]: ...
    def exact_residual_relation(self) -> bool: ...
    @property
    def strategy_version(self) -> bytes: ...
