from collections.abc import Sequence
from typing import TypeAlias

import numpy as np
import numpy.typing as npt

Float64Array: TypeAlias = npt.NDArray[np.float64]
Int64Array: TypeAlias = npt.NDArray[np.int64]
MedialAxisResult: TypeAlias = tuple[
    Float64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Int64Array,
    Float64Array,
    Float64Array,
    Float64Array,
    Int64Array,
    Int64Array,
    Float64Array,
    tuple[bytes, ...],
    Int64Array,
    Int64Array,
    bytes,
    bytes,
]

class MedialAxisConstructionError(RuntimeError): ...
class InvalidReachableDomainInputError(MedialAxisConstructionError): ...
class ReachableArrangementTopologyError(MedialAxisConstructionError): ...
class PocketNotMachinableError(MedialAxisConstructionError): ...
class ReachableMaterialContainmentError(MedialAxisConstructionError): ...
class InvalidMatSamplingPolicyError(MedialAxisConstructionError): ...
class ConicSamplingLimitError(MedialAxisConstructionError): ...
class UnsupportedCanonicalMatLShapeGraphError(MedialAxisConstructionError): ...
class InvalidMatCertificateReplayError(MedialAxisConstructionError): ...
class MissingMatZeroGuideEdgeError(MedialAxisConstructionError): ...
class InvalidMatZeroGuideRecordError(MedialAxisConstructionError): ...
class DuplicateMatZeroGuideEdgeError(MedialAxisConstructionError): ...
class MismatchedMatZeroGuideRecordError(MedialAxisConstructionError): ...
class InvalidMatNeckEvidenceError(MedialAxisConstructionError): ...
class InvalidMatNeckWidthBoundariesError(MedialAxisConstructionError): ...

class SegmentSiteMedialAxis:
    @staticmethod
    def build(
        vertices: Float64Array,
        holes: Sequence[Float64Array],
        tool_radius: float,
        station_spacing: float,
        max_sagitta: float,
        max_refinement_depth: int,
    ) -> SegmentSiteMedialAxis: ...
    @property
    def projection(self) -> MedialAxisResult: ...
    @property
    def node_ids(self) -> tuple[bytes, ...]: ...
    @property
    def edge_ids(self) -> tuple[bytes, ...]: ...
    @property
    def site_ids(self) -> tuple[bytes, ...]: ...
    @property
    def original_dual_ids(self) -> tuple[bytes, ...]: ...
    @property
    def sample_parameter_ids(self) -> tuple[bytes, ...]: ...
    @property
    def neck_owner_ids(self) -> tuple[bytes, ...]: ...
    @property
    def neck_location_tags(self) -> tuple[bytes, ...]: ...
    @property
    def neck_location_edge_ids(self) -> tuple[tuple[bytes, ...], ...]: ...
    @property
    def neck_location_node_ids(self) -> tuple[tuple[bytes, ...], ...]: ...
    @property
    def neck_parameter_root_ids(self) -> tuple[bytes | None, ...]: ...
    @property
    def neck_cut_edge_partitions(
        self,
    ) -> tuple[tuple[tuple[bytes, ...], ...], ...]: ...
    @property
    def neck_defining_site_ids(self) -> tuple[tuple[bytes, ...], ...]: ...
    @property
    def zero_guide_records(self) -> tuple[tuple[bytes, bytes], ...]: ...
    def validate_and_classify_necks(
        self,
        mat_certificate: bytes,
        neck_evidence: tuple[bytes, ...],
        squared_width_boundaries: tuple[bytes, ...],
    ) -> tuple[Int64Array, tuple[bytes, ...]]: ...
    def validate_zero_guide_records(
        self,
        mat_certificate: bytes,
        records: tuple[tuple[bytes, bytes], ...],
    ) -> tuple[bytes, ...]: ...

def segment_site_medial_axis(
    vertices: Float64Array,
    holes: Sequence[Float64Array],
    tool_radius: float,
    station_spacing: float,
    max_sagitta: float,
    max_refinement_depth: int,
) -> MedialAxisResult: ...
